package com.grainite.fundtransfer;

/**
 * This class was generated by GX.
 */
public class Constants {
	public static String APP_NAME = "fund_transfer_1";

	public static String HOST = "10.1.0.5";

	public static int PORT = 5056;

	public static String FUND_TRANSFER_REQUESTS_TOPIC = "fund_transfer_requests_topic";

	public static String FUND_TRANSFER_TABLE = "fund_transfer_1";

	public static String FUND_TRANSFER_TABLE_KEY = "fundTransferKey";

	public static String START_FUND_TRANSFER_ACTION = "startFundTransfer";

	public static String FUND_TRANSFER_REQUESTS_SUBSCRIPTION = "fundTransferRequests";

	public static String HANDLE_DEBIT_ACCOUNT_RESPONSE_ACTION = "handleDebitAccountResponse";

	public static String HANDLE_CREDIT_ACCOUNT_RESPONSE_ACTION = "handleCreditAccountResponse";

	public static String SEND_NOTIFICATIONS_TO_ACCOUNTS = "sendNotificationsToAccounts";

	public static String FINALIZE_DEBIT_ACCOUNT_ACTION = "finalizeDebitAccount";

	public static String ACCOUNT_TABLE = "account_1";

	public static String DEBIT_ACCOUNT_ACTION = "debitAccount";

	public static String CREDIT_ACCOUNT_ACTION = "creditAccount";

	public static String COMPENSATE_DEBIT_ACCOUNT_ACTION = "compensateDebitAccount";

	public static String STATEMENT_TABLE = "statement_table";

	public static String MESSAGE_STATUS_MAP = "message_status_map";

	public static String STATEMENT_KEY = "statement";

	public static String UPDATE_STATEMENT_ACTION = "updateStatement";

	public static String GET_STATEMENT_ACTION = "getStatement";

	public static String FUND_TRANSFER_MAP = "transfers";

	public static String ACCOUNT_LOG_MAP = "account_log_map";

	public static String ACCOUNT_NOTIFICATION_TOPIC = "account_notification_topic";

	public static String TRANSFER_REQUEST_COUNT = "totalTransferRequests";

	public static String DEBIT_PENDING_COUNT = "debitPendingCount";

	public static String DEBIT_FAILED_COUNT = "debitFailedCount";

	public static String CREDIT_FAILED_COUNT = "creditFailedCount";
}
